version: "3"

networks:
  frontend:

services:
  app:
    privileged: true
    build: 
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - /home/dporto/devel:/data
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    environment:
      - APP_USERNAME=caddy
      # compute the password with docker run --rm -it gitkraken-remote_caddy caddy hash-password -plaintext 'aaa'
      # aaa : JDJhJDEwJEVKM0FhUTJvdkdIb2VZdkE0WVhMWS5WMFlkSW5TZTAuL0R4Z3NYdGx1NmgxdmVVVUhUMUhh
      - APP_PASSWORD_HASH=JDJhJDEwJEVKM0FhUTJvdkdIb2VZdkE0WVhMWS5WMFlkSW5TZTAuL0R4Z3NYdGx1NmgxdmVVVUhUMUhh
    volumes:
      - /home/dporto/devel:/data
    ports:
      - 8080:8080


